In [1]:
import numpy as np

### Creating 1D array

In [2]:
a= np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


### Creating 2D array

In [3]:
b= np.array([[1,2,3],
             [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


- ndarray.ndim : the dimension number of the array. It's called rank in Python.
- ndarray.shape : the dimension of the array. It's a series of numbers whose length is determined by the dimension （ndim） of the array. For example, the shape of a one-dimensional array with length n is n. And the shape of an array with n rows and m columns is n,m.
- ndarray.size : the number of all elements in the array.
- ndarray.dtype : the type of the element in the array, such as numpy.int32, numpy.int16, or numpy.float64.
- ndarray.itemsize : the size of each element in the array, in bytes.

In [4]:
b= np.array([[1,2,3],
             [4,5,6]])
c=b.ndim
print("dimension: ",c)

dimension:  2


In [10]:
#Printing itemsize of each element
c= np.array([21,10,6,23])
print(c.itemsize ,"bytes")

4 bytes


In [14]:
#Data type of each array item
c=np.array([[12,2,6,7]])
print(c.dtype)

int32


In [16]:
c=np.array([[12,2,6,7,56,78,89,45]])
print(c.size)
print(c.shape)

8
(1, 8)


In [17]:
arr = np.zeros((3,2), dtype = int)  
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [18]:
arr = np.ones((3,2), dtype = int)  
print(arr) 

[[1 1]
 [1 1]
 [1 1]]


In [19]:
l=[1,2,3,4,5,6,7]  
a = np.asarray(l);  
print(type(a))  
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [20]:
l=(1,2,3,4,5,6,7)     
a = np.asarray(l);  
print(type(a))  
print(a) 

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [21]:
l=[[1,2,3,4,5,6,7],[8,9]]  
a = np.asarray(l);  
print(type(a))  
print(a)

<class 'numpy.ndarray'>
[list([1, 2, 3, 4, 5, 6, 7]) list([8, 9])]


C:\Users\Vedant\Anaconda3\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


#### Numpy.frombuffer

#### This function is used to create an array by using the specified buffer.

In [22]:
l = b'Numpy Tutorial '  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))

<class 'bytes'>
[b'N' b'u' b'm' b'p' b'y' b' ' b'T' b'u' b't' b'o' b'r' b'i' b'a' b'l'
 b' ']
<class 'numpy.ndarray'>


#### Numpy.fromiter

#### This routine is used to create a ndarray by using an iterable object. It returns a one-dimensional ndarray object

In [23]:
list = [0,2,4,6]  
a = iter(list)  
x = np.fromiter(a, dtype = float)  
print(x)  
print(type(x))

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [24]:
# arrays within a range

x = np.arange(5) 
print(x)

[0 1 2 3 4]


In [25]:
arr = np.arange(0,10,2,float)  
print(arr)

[0. 2. 4. 6. 8.]


#### NumPy.linspace

It is similar to the arrange function. However, it doesn't allow us to specify the step size in the syntax. Instead of that, it only returns evenly separated values over a specified period. The system implicitly calculates the step size.

In [31]:
arr = np.linspace(10,20 ,5)
print(arr)

[10.  12.5 15.  17.5 20. ]


In [32]:
# endpoint set to false 
arr = np.linspace(10,20,5 ,endpoint=False)
print(arr)

[10. 12. 14. 16. 18.]


In [36]:
# Find retstep
x = np.linspace(1,10,5, retstep = True) 
print (x) 
#2.25 is the retstep

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


#### Numpy.logspace

It creates an array by using the numbers that are evenly separated on a log scale.

In [40]:
arr = np.logspace(10,30, num=10, endpoint=True)
print(arr)

[1.00000000e+10 1.66810054e+12 2.78255940e+14 4.64158883e+16
 7.74263683e+18 1.29154967e+21 2.15443469e+23 3.59381366e+25
 5.99484250e+27 1.00000000e+30]


In [41]:
arr= np.logspace(10, 20, num = 5,base = 2, endpoint = True)
print(arr)

[1.02400000e+03 5.79261875e+03 3.27680000e+04 1.85363800e+05
 1.04857600e+06]


## Indexing and Slicing

In [44]:
a = np.arange(10) 
s = slice(2,10,2) 
print (a[s])

[2 4 6 8]


In [45]:
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [46]:
# slice single item 

a = np.arange(10) 
b = a[5] 
print(b)

5


In [48]:
a= np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [49]:
a = np.arange(10) 
print(a[2:5])

[2 3 4]


In [50]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [54]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a) 
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:'  )
print(a[...,1] )
print('\n')  

# Now we will slice all items from the second row 
print('The items in the second row are:' )
print(a[1,...]) 
print( '\n'  )

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:') 
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


## Advanced Indexing

In [56]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


The selection includes elements at (0,0), (1,1) and (2,0) from the first array.

In [57]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Original error  array is') 
print(x) 
print('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print('The corner elements of this array are:') 
print (y)

# Here, (0,0 , 0,2 , 3,0 , 3,2 are selected)

Original error  array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [62]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Original error  array is') 
print(x) 
print('\n') 
rows = np.array([[0,1],[1,2]])
cols = np.array([[1,0],[2,1]]) 
y = x[rows,cols] 
   
print('The diamond elements of this array are:') 
print (y)

Original error  array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The diamond elements of this array are:
[[1 3]
 [5 7]]


In [58]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Original array') 
print (x) 
print ('\n')  

# slicing 
z = x[1:4,1:3] 

print ('After slicing, our array becomes:' )
print (z)
print ('\n')  

# using advanced index for column 

y = x[1:4,[1,2]] 

print ('Slicing using advanced index for column:') 
print(y)

Original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]


## Boolean Array Indexing

In [59]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Orginal array is') 
print(x)
print('\n')  

# Now we will print the items greater than 5 
print('The items greater than 5 are:') 
print(x[x > 5])

Orginal array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [63]:

a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


## Numpy Broadcasting

In [64]:
a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,8])  
c= np.multiply(a,b)  
print(c)  

[ 2  8 18 32 50 72 56]


In [65]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  

print("\nprinting array a..")  
print(a)  

print("\nprinting array b..")  

print(b)  

print("\nAdding arrays a and b ..")  
c = a + b
print(c)  


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


## Array Iteration

##### Order of Iteration

There are two ways of storing values into the numpy arrays:

- -F-style order
- -C-style order

In [66]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]]) 

print("Original array:")  
print(a)

print("Iterating over the array:")  
for x in np.nditer(a):  
    print(x,end=' ')  

Original array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [68]:
#Let's see an example of how the numpy Iterator treats the specific orders (F or C).
import numpy as np  
  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
  
print("\n Original array:\n")  
  
print(a)  
  
print("\nPrinting the transpose of the array:\n")  
at = a.T  
  
print(at)  
  
print("\nIterating over the transposed array\n")  
  
for x in np.nditer(at):  
    print(x, end= ' ')  
  
 
print("\nIterating over the C-style array:\n")  
c = at.copy(order = 'C')  
for x in np.nditer(c):  
    print(x,end=' ')  
      
d = at.copy(order = 'F')  
  
print(d)  
print("Iterating over the F-style array: \n")  
for x in np.nditer(d):  
    print(x,end=' ')  


 Original array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 [[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
Iterating over the F-style array: 

1 2 3 4 2 4 5 6 10 20 39 3 

In [69]:
# We can mention the order 'C' or 'F' while defining the Iterator object itself. let's Consider the an example. 
  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
  
print("\nPrinting the array:\n")  
  
print(a)  
  
print("\nPrinting the transpose of the array:\n")  
at = a.T  
  
print(at)  
  
print("\nIterating over the transposed array\n")  
  
for x in np.nditer(at):  
    print(x, end= ' ')  

print("\nIterating over the C-style array:\n")  
for x in np.nditer(at, order = 'C'):  
    print(x,end=' ')  


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 

## Mathematical Functions

In [71]:
# Trigonometry
arr = np.array([0, 30, 60, 90, 120, 150, 180])  

print("\nThe sin value of the angles",end = " ")  
print(np.sin(arr * np.pi/180)) 

print("\nThe cosine value of the angles",end = " ")  
print(np.cos(arr * np.pi/180))

print("\nThe tangent value of the angles",end = " ")  
print(np.tan(arr * np.pi/180))  


The sin value of the angles [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

The cosine value of the angles [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

The tangent value of the angles [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [72]:
# Rounding

arr = np.array([12.202, 90.23120, 123.020, 23.202])  

print("printing the original array values:",end = " ")  
print(arr)  

print("Array values rounded off to 2 decimal position",np.around(arr, 2))  

print("Array values rounded off to -1 decimal position",np.around(arr, -1))

printing the original array values: [ 12.202   90.2312 123.02    23.202 ]
Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


In [73]:
#floor
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.floor(arr))  

[ 12.  90. 123.  23.]


In [74]:
#Ceil
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.ceil(arr)) 

[ 13.  91. 124.  24.]


## Statistical functions

In [75]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("The original array:\n")  
print(a)  

# Maximum and Minimum  
print("\nThe minimum element among the array:",np.amin(a))  
print("The maximum element among the array:",np.amax(a))  
  
# Maximum and Minimum along axis 0 
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("The maximum element among the rows of array",np.amax(a,0))  
  
# Maximum and Minimum along axis 1
print("\nThe minimum element among the columns of array",np.amin(a,1))  
print("The maximum element among the columns of array",np.amax(a,1)) 

The original array:

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2
The maximum element among the array: 80

The minimum element among the rows of array [ 2 10 10]
The maximum element among the rows of array [80 43 31]

The minimum element among the columns of array [ 2 31 10]
The maximum element among the columns of array [20 80 43]


In [76]:
# peak to peak function
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("Original array:\n",a)  
  
print("\nptp value along axis 1:",np.ptp(a,1))  
  
print("ptp value along axis 0:",np.ptp(a,0)) 

Original array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


In [77]:
#percentile

a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("Array:\n",a)  
  
print("\nPercentile along axis 0",np.percentile(a, 10,0))  
  
print("Percentile along axis 1",np.percentile(a, 10, 1))

Array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

Percentile along axis 0 [ 6.  16.6 12. ]
Percentile along axis 1 [ 3.6 33.4 12.4]


In [78]:
# Calculating median, mean, and average of array items
  
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
  
print("Array:\n",a)  
  
print("\nMedian of array along axis 0:",np.median(a,0))  

print("Mean of array along axis 0:",np.mean(a,0))  

print("Average of array along axis 1:",np.average(a,1))  

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]
Mean of array along axis 0: [4. 5. 6.]
Average of array along axis 1: [2. 5. 8.]


## NumPy Sorting and Searching

In [79]:
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
  
print("Sorting along the columns:")  
print(np.sort(a))  
  
print("Sorting along the rows:")  
print(np.sort(a, 0))  
  
data_type = np.dtype([('name', 'S10'),('marks',int)])  
  
arr = np.array([('Mukesh',200),('John',251)],dtype = data_type)  
  
print("Sorting data ordered by name")  
  
print(np.sort(arr,order = 'name'))  

Sorting along the columns:
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the rows:
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
Sorting data ordered by name
[(b'John', 251) (b'Mukesh', 200)]


In [80]:
#argsort
a = np.array([90, 29, 89, 12])  
  
print("Original array:\n",a)  
  
sort_ind = np.argsort(a)  
  
print("Printing indices of sorted data\n",sort_ind)  
  
sort_a = a[sort_ind]  
  
print("printing sorted array")  
  
for i in sort_ind:  
    print(a[i],end = " ")  

Original array:
 [90 29 89 12]
Printing indices of sorted data
 [3 1 2 0]
printing sorted array
12 29 89 90 

In [81]:
# lex sort -This function is used to sort the array using the sequence of keys indirectly. 
# This function performs similarly to the numpy.argsort() which returns the array of indices of sorted data.
a = np.array(['a','b','c','d','e'])  
  
b = np.array([12, 90, 380, 12, 211])  
  
ind = np.lexsort((a,b))  
  
print("printing indices of sorted data")  
  
print(ind)  
  
print("using the indices to sort the array")  
  
for i in ind:  
    print(a[i],b[i])  

printing indices of sorted data
[0 3 1 4 2]
using the indices to sort the array
a 12
d 12
b 90
e 211
c 380


In [82]:
b = np.array([12, 90, 380, 12, 211])  
  
print("printing original array",b)  
  
print("printing location of the non-zero elements")  
  
print(b.nonzero()) 

printing original array [ 12  90 380  12 211]
printing location of the non-zero elements
(array([0, 1, 2, 3, 4], dtype=int64),)


In [83]:
b = np.array([12, 90, 380, 12, 211])  
  
print(np.where(b>12))  
  
c = np.array([[20, 24],[21, 23]])  
  
print(np.where(c>20))

(array([1, 2, 4], dtype=int64),)
(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))


## Linear Algebra

In [84]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)  

[[3400 6200]
 [ 374  712]]


In [85]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)

5528


In [86]:
#np.inner
#This function returns the sum of the product of inner elements of the one-dimensional array.
# For n-dimensional arrays, it returns the sum of the product of elements over the last axis
a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner) 

130


In [87]:
# Numpy.matmul() function

# It is used to return the multiplication of the two matrices. 
# It gives an error if the shape of both matrices is not aligned for multiplication. Consider the following example.

a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul)  

[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


In [88]:
#determinant
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a)) 

-2.0000000000000004


In [90]:
#multiplicative inverse
a = np.array([[1,2],[3,4]])  
print("Original array:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b) 

Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## NumPy - Copies & Views

In [1]:
import numpy as np 
a = np.arange(6) 

print('Our array is:') 
print(a)  

print('Applying id() function:')
print(id(a))  

print('a is assigned to b:')
b = a 
print(b)  

print('b has same id():') 
print(id(b))

print('Change shape of b:') 
b.shape = 3,2 
print(b)  

print('Shape of a also gets changed:') 
print(a)

Our array is:
[0 1 2 3 4 5]
Applying id() function:
2476716678864
a is assigned to b:
[0 1 2 3 4 5]
b has same id():
2476716678864
Change shape of b:
[[0 1]
 [2 3]
 [4 5]]
Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]


In [2]:
#view or shallow copy
a = np.arange(6).reshape(3,2) 

print('Array a:') 
print(a)  

print('Create view of a:') 
b = a.view() 
print(b) 

print('id() for both the arrays are different:') 
print('id() of a:')
print(id(a))
print('id() of b:') 
print(id(b))  

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

print('Shape of b:') 
print(b)  

print('Shape of a:')
print(a)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
2476721763216
id() of b:
2476721763312
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]


In [3]:
a = np.arange(6).reshape(3,2) 

print('Array a:')
print(a)

print('Create view of a:') 
b = a.view() 
print(b)

print('id() for both the arrays are different:')
print('id() of a:')
print(id(a))
print('id() of b:') 
print(id(b))  

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

print('Shape of b:') 
print(b)

print('Shape of a:')
print(a)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
2476721763984
id() of b:
2476721763216
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]


In [4]:
a = np.array([[10,10], [2,3], [4,5]]) 

print('Our array is:') 
print(a)  

print('Create a slice:') 
s = a[:, :2] 
print(s)

Our array is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a slice:
[[10 10]
 [ 2  3]
 [ 4  5]]


In [5]:
# deep copy

a = np.array([[10,10], [2,3], [4,5]]) 

print('Array a is:') 
print(a)

print('Create a deep copy of a:') 
b = a.copy() 
print('Array b is:') 
print(b) 

#b does not share any memory of a 
print('Can we write b is a')
print(b is a)  

print('Change the contents of b:') 
b[0,0] = 100 

print('Modified array b:')
print(b)

print('a remains unchanged:') 
print(a)

Array a is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a deep copy of a:
Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Can we write b is a
False
Change the contents of b:
Modified array b:
[[100  10]
 [  2   3]
 [  4   5]]
a remains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]


In [6]:
#Concatenate function

x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  


z=np.concatenate((x,y))  
print(z)

[[ 1  2]
 [ 3  4]
 [12 30]]


In [7]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  

z=np.concatenate((x,y.T), axis=1)  
print(z)  

# In this example, the '.T' used to change the rows into columns and columns into rows.

[[ 1  2 12]
 [ 3  4 30]]


In [8]:

a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  

c=np.append(a,b)  
print(c)

[10 20 30 40 50 60 70 80 90 11 21 31 42 52 62 73 83 93]


In [9]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  

c=np.append(a,b,axis=0)  
print(c)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [11 21 31]
 [42 52 62]
 [73 83 93]]


In [10]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  

c=np.append(a,b,axis=1)  
print(c)  

[[10 20 30 11 21 31]
 [40 50 60 42 52 62]
 [70 80 90 73 83 93]]
